juvelissimo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('juvelissimoapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

juvelissimoapp/urls.py
from django.urls import path, re_path, reverse_lazy
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView

from juvelissimoapp.views import (
    base_view, 
    category_view, 
    product_view, 
    cart_view,
    add_to_cart_view, 
    remove_from_cart_view, 
    change_item_quantity, 
    checkout_view,
    order_create_view,
    make_order_view,
    account_view,
    registration_view,
    login_view,
    add_product_view,
    make_product_view,
    delete_product_view
    )

urlpatterns = [
    re_path(r'^category/(?P<category_slug>[-\w]+)/$', category_view, name='category_detail'),
    re_path(r'^product/(?P<product_slug>[-\w]+)/$', product_view, name='product_detail'),
    re_path(r'^add_to_cart/$', add_to_cart_view, name='add_to_cart'),
    re_path(r'^remove_from_cart/$', remove_from_cart_view, name='remove_from_cart'),
    re_path(r'^change_item_quantity/$', change_item_quantity, name='change_item_quantity'),
    re_path(r'^cart/$', cart_view, name='cart'),
    re_path(r'^checkout/$', checkout_view, name='checkout'),
    re_path(r'^order/$', order_create_view, name='create_order'),
    re_path(r'^thank_you/$', TemplateView.as_view(template_name='thank_you.html'), name='thank_you'),
    re_path(r'^make_order/$', make_order_view, name='make_order'),
    re_path(r'^account/$', account_view, name='account'),
    re_path(r'^registration/$', registration_view, name='registration'),
    re_path(r'^login/$', login_view, name='login'),
    re_path(r'^logout/$', LogoutView.as_view(next_page=reverse_lazy('base')), name='logout'),
    re_path(r'^add_product/$', add_product_view, name='add_product'),
    re_path(r'^make_product/$', make_product_view, name='make_product'),
    re_path(r'^product_is_made/$', TemplateView.as_view(template_name='product_is_made.html'), name='product_is_made'),
    re_path(r'^delete_product/(?P<product_slug>[-\w]+)$', delete_product_view, name='delete_product'),
    re_path(r'^$', base_view, name='base'),
]

juvelissimoapp/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.urls import reverse
from django.conf import settings
from transliterate import translit
from decimal import Decimal
from django.contrib.postgres.fields import JSONField

# Create your models here.


class Category(models.Model):
    
    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("category_detail", kwargs={"category_slug" : self.slug})


def pre_save_category_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(translit(str(instance.name), reversed=True))
        instance.slug = slug

pre_save.connect(pre_save_category_slug, sender=Category)

def image_folder(instance, filename):
    filename = instance.slug + '.' + filename.split('.')[1]
    return "{0}/{1}".format(instance.slug, filename)


class ProductManager(models.Manager):

    def all(self, *args, **kwargs):
        return super(ProductManager, self).get_queryset().filter(available=True)


class Product(models.Model):
    category = models.ForeignKey(Category, models.CASCADE)
    slug = models.SlugField(blank=True)
    description = models.TextField()
    image = models.ImageField(upload_to=image_folder)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    available = models.BooleanField(default=True)
    data = JSONField(default=dict)

    def __str__(self):
        return self.data['title']

    def get_absolute_url(self):
        return reverse("product_detail", kwargs={"product_slug" : self.slug})

    def delete_url(self):
        return reverse("delete_product", kwargs={"product_slug" : self.slug})


def pre_save_product_slug(sender, instance, *args, **kwargs):
    if not instance.slug:
        slug = slugify(translit(str(instance.data['title']), reversed=True))
        instance.slug = slug
    

pre_save.connect(pre_save_product_slug, sender=Product)


class CartItem(models.Model):

    product = models.ForeignKey(Product, models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    item_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return "Cart item for product {0}".format(self.product.data['title'])


class Cart(models.Model):
    
    items = models.ManyToManyField(CartItem, blank=True)
    cart_total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)

    def __str__(self):
        return str(self.id)

    def add_to_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        new_item, _ = CartItem.objects.get_or_create(product=product, item_total=product.price)
        if new_item not in cart.items.all():
            cart.items.add(new_item)
            cart.save()
    
    def remove_from_cart(self, product_slug):
        cart = self
        product = Product.objects.get(slug=product_slug)
        for cart_item in cart.items.all():
            if cart_item.product == product:
                cart.items.remove(cart_item)
                cart.save()


    def change_quantity(self, quantity, item_id):
        cart = self
        cart_item = CartItem.objects.get(id=int(item_id))
        cart_item.quantity = int(quantity)
        cart_item.item_total = int(quantity) * Decimal(cart_item.product.price)
        cart_item.save()
        new_cart_total = 0.00
        for item in cart.items.all():
            new_cart_total += float(item.item_total)
        cart.cart_total = new_cart_total
        cart.save()

ORDER_STATUS_CHOICES = (
    ('Принят в обработку', 'Принят в обработку'),
    ('Выполняется', 'Выполняется'),
    ('Оплачен', 'Оплачен')
)

class Order(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, models.CASCADE)
    items = models.ForeignKey(Cart, models.CASCADE)
    total = models.DecimalField(max_digits=9, decimal_places=2, default=0.00)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255)
    buying_type = models.CharField(max_length=40, choices=(('Самовывоз', 'Самовывоз'),('Доставка', 'Доставка')), default='Самовывоз')
    date = models.DateTimeField(auto_now_add=True)
    comments = models.TextField()
    status = models.CharField(max_length=100, choices=ORDER_STATUS_CHOICES, default=ORDER_STATUS_CHOICES[0][0])

    def __str__(self):
        return "Заказ № {0}".format(str(self.id))

juvelissimoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth import login, authenticate
from decimal import Decimal
from juvelissimoapp.models import Category, Product, CartItem, Cart, Order
from juvelissimoapp.forms import OrderForm, RegistrationForm, LoginForm, ProductForm
from django.contrib.auth.decorators import permission_required
from django.utils.text import slugify
from django.contrib.postgres.fields import JSONField
# Create your views here.


def base_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    products = Product.objects.all()
    is_moderator = False
    print(request.user)
    if request.user.groups.filter(name='Moderators').exists():
        is_moderator = True
    context = {
        'categories' : categories,
        'products' : products,
        'cart' : cart,
        'is_moderator' : is_moderator,
    }
    return render(request, 'base.html', context)


def product_view(request, product_slug):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    is_moderator = False
    if request.user.groups.filter(name='Moderators').exists():
        is_moderator = True
    categories = Category.objects.all()
    product = Product.objects.get(slug=product_slug)
    context = {
        'categories' : categories,
        'product' : product,
        'cart' : cart,
        'is_moderator' : is_moderator,
    }
    return render(request, 'product.html', context)


def category_view(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    categories = Category.objects.all()
    products_of_category = Product.objects.filter(category=category)
    query = request.GET.get('query')
    
    if query:
        products_of_category = products_of_category.filter(data__title__icontains=query)

    context = {
        'category' : category,
        'products_of_category': products_of_category,
        'categories' : categories,
    }
    return render(request, 'category.html', context)


def cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    categories = Category.objects.all()
    context = {
        'cart' : cart,
        'categories' : categories,
    }
    return render(request, 'cart.html', context)


def add_to_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.add_to_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total': cart.items.count(), 'cart_total_price': cart.cart_total})


def remove_from_cart_view(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    product_slug = request.GET.get('product_slug')
    product = Product.objects.get(slug=product_slug)
    cart.remove_from_cart(product.slug)
    new_cart_total = 0.00
    for item in cart.items.all():
        new_cart_total += float(item.item_total)
    cart.cart_total = new_cart_total
    cart.save()
    return JsonResponse({'cart_total': cart.items.count(), 'cart_total_price': cart.cart_total})


def change_item_quantity(request):
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    quantity = request.GET.get('quantity')
    item_id = request.GET.get('item_id')
    cart.change_quantity(quantity, item_id)
    cart_item = CartItem.objects.get(id=int(item_id))
    return JsonResponse(
        {'cart_total': cart.items.count(), 
        'item_total': cart_item.item_total,
        'cart_total_price': cart.cart_total})


def checkout_view(request):
    categories = Category.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    context = {
        'cart' : cart,
        'categories' : categories,
    }
    return render(request, 'checkout.html', context)


def order_create_view(request):
    categories = Category.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    context = {
        'form' : form,
        'cart' : cart,
        'categories' : categories,
    }
    return render(request, 'order.html', context)


def make_order_view(request):
    categories = Category.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id
        cart = Cart.objects.get(id=cart_id)
    form = OrderForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data['name']
        last_name = form.cleaned_data['last_name']
        phone = form.cleaned_data['phone']
        buying_type = form.cleaned_data['buying_type']
        address = form.cleaned_data['address']
        comments = form.cleaned_data['comments']
        new_order = Order.objects.create(
            user = request.user,
            items = cart,
            total = cart.cart_total,
            first_name = name,
            last_name = last_name,
            phone = phone,
            address = address,
            buying_type = buying_type,
            comments = comments
        )
        del request.session['cart_id']
        del request.session['total']
        return HttpResponseRedirect(reverse('thank_you'))
    return render(request, 'order.html', {'categories' : categories})


def account_view(request):
    categories = Category.objects.all()
    order = Order.objects.filter(user=request.user).order_by('-id')
    context = {
        'order' : order,
        'categories' : categories,
    }
    return render(request, 'account.html', context)


def registration_view(request):
    categories = Category.objects.all()
    form = RegistrationForm(request.POST or None)
    if form.is_valid():
        new_user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        email = form.cleaned_data['email']
        first_name = form.cleaned_data['first_name']
        last_name = form.cleaned_data['last_name']
        new_user.username = username
        new_user.set_password(password)
        new_user.first_name = first_name
        new_user.last_name = last_name
        new_user.email = email
        new_user.save()
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    context = {
        'form' : form,
        'categories' : categories,
    }
    return render(request, 'registration.html', context)


def login_view(request):
    categories = Category.objects.all()
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        login_user = authenticate(username=username, password=password)
        if login_user:
            login(request, login_user)
            return HttpResponseRedirect(reverse('base'))
    context = {
        'form' : form,
        'categories' : categories,
    }
    return render(request, 'login.html', context)

@permission_required('juvelissimoapp.add_product', raise_exception=True)
def add_product_view(request):
    categories = Category.objects.all()
    try:
        cart_id = request.session['cart_id']
        cart = Cart.objects.get(id=cart_id)
        request.session['total'] = cart.items.count()
    except:
        cart = Cart()
        cart.save()
        cart_id = cart.id
        request.session['cart_id'] = cart_id

juvelissimoapp/templates/account.html
{% extends 'base.html' %}

{% block content %}

<br>
<h3 class='text-center'>Личный кабинет пользователя {{ request.user }}</h3>
<hr>
<h4 class='text-center'>Ваши заказы</h4>
<table class='table'>
<tr style='background: lightblue;'>
    <td class='text-center'>Номер заказа</td>
    <td class='text-center'>Дата заказа</td>
    <td class='text-center'>Статус заказа</td>
    <td class='text-center'>Стоимость заказа</td>
    <td class='text-center'>Детали заказа</td>
</tr>
{% for item in order %}
<tr>
    <td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.id }}</td>
    <td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.date }}</td>
    <td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.status }}</td>
    <td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'>{{ item.total }} BYN</td>
    <td class='text-center' style='padding-top: 20px; padding-bottom: 20px;'><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal-{{ item.id }}">
  Детали заказа
</button></td>
{% endfor %}
</table>

<!-- Modal -->
{% for item in order %}
<div class="modal fade" id="myModal-{{ item.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Заказ № {{ item.id }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class='table'>
            {% for order_item in item.items.items.all %}
                <tr>
                    <td>{{ order_item.product.data.title }}</td>
                    <td>{{ order_item.quantity }} шт.</td>
                    <td>{{ order_item.item_total }} BYN</td>
                </tr>
            {% endfor %}
            <tr>
                <td></td>
                <td>Итого</td>
                <td><strong>{{ item.items.cart_total }} BYN</strong></td>
            </tr>
        </table>
        <h3>Заказчик</h3>
        <p>Имя: {{ item.first_name }}</p>
        <p>Фамилия: {{ item.last_name }}</p>
        <p>Телефон: {{ item.phone }}</p>
        <h3>Тип доставки</h3>
        <p>{% if item.buying_type == 'self' %} Самовывоз {% else %} Доставка {% endif %}</p>
        <p>{% if item.buying_type == 'delivery' %} {{ item.address }} {% endif %}</p>
        <h3>Комментарии к заказу</h3>
        <p>{{ item.comments }}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
      </div>
    </div>
  </div>
</div>
{% endfor %}
<br>
<br>
{% endblock content %}

juvelissimoapp/templates/add_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<hr>
<h3 class='text-center'>Добавление изделия</h3>
<hr>
<form action='{% url 'make_product' %}' method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type='submit' class='btn btn-success' value='Добавить продукт'>
</form>
<br>

{% endblock content %}

juvelissimoapp/templates/cart.html
{% extends 'base.html' %}

{% block content %}
<br>
<h3 class='text-center'>Ваша корзина</h3>
<br>
{% if cart.items.count > 0 %}
<div class='my-cart'>
    <table class='table'>
    <tr>
        <td class='text-center'><strong>Товар</strong></td>
        <td class='text-center'><strong>Кол-во</strong></td>
        <td class='text-center'><strong>Цена</strong></td>
        <td class='text-center'><strong></strong></td>
    </tr>
    {% for item in cart.items.all %}
    <tr class='cart-item-{{ item.product.id }}' id={{ item.product.slug }}>
        <td class='text-center'>{{ item.product.data.title }}</td>
        <td class='text-center'>
            <form action='' method='GET'>
                <input type='number' name='quantity' class='cart-item-quantity' data-id='{{ item.id }}' value='{{ item.quantity }}' min='1' style='width: 50px;'>        
            </form> 
        </td>
        <td class='text-center' id='cart-item-total-{{ item.id }}'>{{ item.item_total }} BYN</td>
        <td class='text-center'><a href='#' class='remove_from_cart' data-slug='{{ item.product.slug }}'><button class='btn btn-danger'>Удалить</button></a></td>
    </tr>
    {% endfor %}
    <tr>
        <td></td>
        <td class='text-center'><strong>Итого:</strong></td>
        <td class='text-center' id='cart-total-price'><strong>{{ cart.cart_total }} BYN</strong></td>
        <td></td>
    </tr>
    </table>
    <br>
    <a href='{% url 'checkout' %}'><button class='btn btn-info'>Предварительный заказ</button></a>
</div>
<br>
<h3 class='cart-empty'></h3>
{% else %}
<h3 class='text-center'>Ваша корзина пуста</h3>
{% endif %}
<script>
    $(document).ready(function(){
        $('.cart-empty').css('display', 'none')
        $('.remove_from_cart').on('click', function(e){
            e.preventDefault()
            product_slug = $(this).attr('data-slug')
            data = {
                product_slug: product_slug
            }

            $.ajax({
                type: "GET",
                url: '{% url 'remove_from_cart' %}',
                data: data,
                success: function(data) {
                    $("#cart_count").html(data.cart_total)
                    $('#' + product_slug).remove()
                    $('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(2) + ' BYN </strong>')
                    if (parseInt(data.cart_total) == 0) {
                        $('.my-cart').css('display', 'none')
                        $('.cart-empty').css('display', 'block')
                        $('.cart-empty').html('<h3 class="text-center">Ваша корзина пуста</h3>')
                    }
                }
            })
        })
    })
</script>
<script>
    $(document).ready(function(){
        $('.cart-item-quantity').on('click', function(){
            quantity = $(this).val()
            item_id = $(this).attr('data-id')
            data = {
                quantity: quantity,
                item_id: item_id
            }
            $.ajax({
                type: "GET",
                url: '{% url 'change_item_quantity' %}',
                data: data,
                success: function(data) {
                    $('#cart-item-total-' + item_id).html(parseFloat(data.item_total).toFixed(2) + ' BYN')
                    $('#cart-total-price').html('<strong>' + parseFloat(data.cart_total_price).toFixed(2) + ' BYN </strong>')
                }
            })
        })
    })
</script>
{% endblock content %}

juvelissimoapp/templates/category.html
{% extends 'base.html' %}

{% block content %}
<div class='col-sm-12'>
    <br>
    <h2>{{ category.name }}</h2>
    <form type='GET' class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" id="product-search" name="query" type="search" placeholder="" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Найти</button>
    </div>
    <hr>
    <div class='row products_list'>
    {% for product in products_of_category %}
    <div class='col-sm-4'>
        <a href='{{ product.get_absolute_url }}'><img src='{{ product.image.url }}' style='width:100%'></a>
        <h4 class='text-center'><a href="{{ product.get_absolute_url }}">{{ product.data.title }}</a></h4>
        <p class='text-center' style='font-size: 25px;'>Цена: <strong>{{ product.price }}</strong> BYN</p>
        <p class='text-center' ><a href='#' class='add_to_cart' data-slug='{{ product.slug }}'><button class='btn btn-danger'>Добавить в корзину</button></a></p>
    </div>
    {% endfor %}
    </div>
</div>
<script>
    $(document).ready(function(){
        $('.add_to_cart').on('click', function(e){
            e.preventDefault()
            product_slug = $(this).attr('data-slug')
            data = {
                product_slug: product_slug
            }
            $.ajax({
                type: "GET",
                url: '{% url 'add_to_cart' %}',
                data: data,
                success: function(data) {
                    $("#cart_count").html(data.cart_total)
                }
            })
        })
    })
</script>
{% endblock content  %}

juvelissimoapp/templates/checkout.html
{% extends 'base.html' %}

{% block content %}
<br>
<h3 class='text-center'>Ваш заказ</h3>
<br>
<table class='table'>
<tr>
    <td class='text-center'><strong>Товар</strong></td>
    <td class='text-center'><strong>Кол-во</strong></td>
    <td class='text-center'><strong>Цена</strong></td>
    <td class='text-center'><strong></strong></td>
</tr>
{% for item in cart.items.all %}
<tr>
    <td class='text-center'>{{ item.product.data.title }}</td>
    <td class='text-center'>{{ item.quantity }}</td>
    <td class='text-center'>{{ item.item_total }} BYN</td>
    <td></td>
</tr>
{% endfor %}
<tr>
    <td></td>
    <td class='text-center'><strong>Итого:</strong></td>
    <td class='text-center'><strong>{{ cart.cart_total }} BYN</strong></td>
    <td></td>
</tr>
</table>
{% if request.user.is_authenticated %}
    <a href='{% url 'create_order' %}'><button class='btn btn-success'>Оформить заказ</button></a>
{% else %}
    <p>Заказывать товар могут только авторизованные пользователи. Пожалуйста, <a href='{% url 'login' %}'>войдите</a> или <a href='{% url 'registration' %}'>зарегистрируйтесь</a></p>
{% endif %}
<br>
<br>
{% endblock content %}

juvelissimoapp/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<br>
<h3 class='text-center'>Авторизация</h3>
<div class='container'>
    <div class='col-sm-8 offset-sm-2'>
        <hr>
        <form action='' method='POST'>
            {% csrf_token %}
            {{ form|crispy }}
            <input type='submit' class='btn btn-success btn-block' value='Войти в систему'>
        </form>
    </div>
    <br>
</div>

{% endblock content %}

juvelissimoapp/templates/order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<hr>
<h3 class='text-center'>Оформление заказа</h3>
<hr>
<form action='{% url 'make_order' %}' method="POST">
{% csrf_token %}
<div class='row'>
    <div class='col-sm-4'>
        {{ form.name|as_crispy_field }}
    </div>
    <div class='col-sm-4'>
        {{ form.last_name|as_crispy_field }}
    </div>
    <div class='col-sm-4'>
        {{ form.phone|as_crispy_field }}
    </div>
</div>
{{ form.buying_type|as_crispy_field }}
{{ form.address|as_crispy_field }}
{{ form.date|as_crispy_field }}
{{ form.comments|as_crispy_field }}
<input type='submit' class='btn btn-success' value='Оформить заказ'>
</form>
<br>

<script>
    $(document).ready(function(){
        $('#div_id_address').css('display', 'none')
        $('#id_buying_type').on('click', function(){
            buying_type = $(this).val()
            if (buying_type == 'delivery') {
                $('#div_id_address').css('display', 'block')
            } else {
                $('#div_id_address').css('display', 'none')
            }
        })
        $('#id_date_month').css('width', '100px')
        $('#id_date_month').css('display', 'inline')
        $('#id_date_year').css('width', '100px')
        $('#id_date_year').css('display', 'inline')
        $('#id_date_day').css('width', '100px')
        $('#id_date_day').css('display', 'inline')
    })
</script>
{% endblock content %}

juvelissimoapp/templates/product_is_made.html
{% extends 'base.html' %}

{% block content %}

<br>
<div class='col-sl-8 col-sm-offset-2'>
	<h3 class='text-center'>Товар добавлен в магазин</h3>
	<p class='text-center'><a href='/'><button class='btn btn-default'>Вернуться на главную</button></a></p>
</div>

{% endblock content %}

juvelissimoapp/templates/registration.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<br>
<h3 class='text-center'>Регистрация</h3>
<div class='container'>
    <div class='col-sm-8 offset-sm-2'>
        <hr>
        <form action='' method='POST'>
            {% csrf_token %}
            {{ form|crispy }}
            <input type='submit' class='btn btn-success btn-block' value='Зарегистрироваться'>
        </form>
    </div>
    <br>
</div>

{% endblock content %}